#INTRO
#Set up is quick and easy. Simply replace any example text with your nonprofit's information.
#To leave a field blank, simply remove everything after the colon (:) or place a hashtag (#) at the start of the line.
#If you see '> # Enter on the next line', be sure the next line remains indented two spaces.

#REQUIRED
org_name: M2237.co
org_summary: > # Enter your summary on the next line. Be sure to indent by two spaces.
  Putting Christ First in AI Research
org_full_description: > # Enter your description on the next line. Be sure to indent by two spaces.
  As followers of Christ, we are called to engage the world around us with the unchanging gospel message of hope, reconciliation and love for our neighbors. Tools like technology are able to aid us in learning and understanding what it means to live according to the scripture. Advances in technology and research have alowed our generation to expierence the word, and miracles of our creater at an uncomprehendable scale. We know technology can also be designed and used in ways that dishonor God and devalue our fellow image-bearers. Evangelical Christians hold fast to the inerrant and infallible Word of God, which states that every human being is made in Godâ€™s image and thus has infinite value and worth in the eyes of their Creator. Our research relates to how we all view God, ourselves, and the tools that God has given us the ability to create. Every day, artificial Intelligence becomes more advanced and technology research becomes faster. As we learn more about artificial intelligence, it learns more about us as well. We are scientists, computer programmers, tech enthusiests, and AI research engineers, but above all else, we are followers of Christ. As we move into a new era of technologial innovation, our mission is to preserve the word of God and the message of Christ our Savior. Matthew 28:18-20

#OPTIONAL
#Non US-address support coming soon
org_general_email_inbox: Send us your Blessing
org_street_address: 1355 Market Street #Please include suite number on the line below
org_address_suite: Suite 900
org_city: San Francisco
org_state: CA
org_zip: > # Enter zip on next line. Be sure to indent by two spaces.
  94103
org_phone: > # Enter phone on next line. Be sure to indent by two spaces.
  (123) 456-7890

#SOCIAL MEDIA
org_twitter_username: M2237
org_facebook_username: M2237
org_instagram_username:

#TAX STATUS
#Your site will display an appropriate message below the Donate section
#If your organization is fiscally sponsored, enter true below and add your sponsor's name. Otherwise enter false.
fiscal_sponsor: false
fiscal_sponsor_name:
#If your organization is currently registered as a 501(c)3 organization, enter true below. Otherwise enter false. Enter false if you have a fiscal sponsor.
501c3: true

#ONLINE DONATIONS & EMAIL SIGNUPS
#To use these services, enter the required usernames. For further instructions, consult the README file.
#If you do not wish to use a service, simply remove everything after the colon (:), leaving the item blank
donorbox_campaign_name: free-template-demo
tinyletter_username: interestingnonprofits

#SEARCH ENGINES
#Changing this next setting to 'true' will allow your site to be indexed by search engines (like Google)
publish: false

#THEME
#Select one of the five color schemes (default, one, two, three, or four)
theme: default

# *** DO NOT CHANGE ANYTHING BELOW THIS LINE ***

# Unless you know what you're doing, no need to change anything below
# Build settings
baseurl: "" # the subpath of your site, e.g. /blog/
markdown: kramdown
kramdown:
  input: GFM

sass:
    sass_dir: assets/_sass
    style: compressed

#Features under development
#These are not yet fully supported, but should give you a head start if you know what you're doing
paypal_button_id: #Not yet available
smartergiving_id: #Not yet available
#mailchimp_embed_code: > # Enter Mailchimp post url on next line.
#  //getkyn.us5.list-manage.com/subscribe/post?u=1407d7ee4cd0d47986cd54315&amp;id=cdc32b64fe
#mailchimp_spam_guard: b_753395b9f963c9ea2d6980b7c_9e1559c2f0
